# Generated by Django 6.1.1 on 2026-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alert_response_alter_alert_status'),
        ('jobs', '0003_scanrun_toolexecution_assetobservation'),
        ('targets', '0002_target_notification_config_target_scan_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='targets.target'),
        ),
        migrations.AddField(
            model_name='event',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='new_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='old_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='scan_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='jobs.scanrun'),
        ),
    ]
