# Generated by Django 5.2.17 on 2026-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alert_target_event_correlation_id_event_new_state_and_more"),
        ("targets", "0006_seed_owner_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alert",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="outcome_reason",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["target", "status"], name="events_aler_target__921b3b_idx"
            ),
        ),
    ]
