# Generated by Django 6.1.1 on 2026-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='notification_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='target',
            name='scan_profile',
            field=models.CharField(db_index=True, default='balanced', max_length=16),
        ),
        migrations.AddField(
            model_name='target',
            name='verify_tls',
            field=models.BooleanField(default=True),
        ),
    ]
