# Generated by Django 6.1.1 on 2026-09-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_notification_config_target_scan_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='reconciliation_grace_days',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
