# Generated by Django 6.1.1 on 2026-09-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_target_reconciliation_grace_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='authorization_status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='PENDING', max_length=16),
        ),
    ]
