# Generated by Django 5.2.17 on 2026-09-28 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("targets", "0004_alter_target_authorization_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("OPERATOR", "Operator"),
                            ("VIEWER", "Viewer"),
                        ],
                        db_index=True,
                        default="VIEWER",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["target_id", "user_id"],
            },
        ),
        migrations.AddField(
            model_name="target",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="target",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="target",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("DISABLED", "Disabled"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="target",
            index=models.Index(
                fields=["status", "archived_at"], name="targets_tar_status_52ec17_idx"
            ),
        ),
        migrations.AddField(
            model_name="targetmembership",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="targets.target",
            ),
        ),
        migrations.AddField(
            model_name="targetmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="targetmembership",
            index=models.Index(
                fields=["target", "role"], name="targets_tar_target__ada032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="targetmembership",
            index=models.Index(
                fields=["user", "role"], name="targets_tar_user_id_da84c3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="targetmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "target"), name="uniq_membership_user_target"
            ),
        ),
    ]
