# Generated by Django 5.2.17 on 2026-09-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_global_target_admin",
            field=models.BooleanField(default=False),
        ),
    ]
