# Generated by Django 6.1.1 on 2026-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_scanjob_asset_type_scanjob_asset_value_and_more'),
        ('targets', '0002_target_notification_config_target_scan_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('DISCOVERY', 'DISCOVERY'), ('MONITORING', 'MONITORING'), ('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE'), ('FULL', 'FULL'), ('VALIDATION', 'VALIDATION')], db_index=True, default='MONITORING', max_length=16)),
                ('profile', models.CharField(db_index=True, default='balanced', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('DEGRADED', 'Degraded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('trigger', models.CharField(db_index=True, default='manual', max_length=32)),
                ('configuration_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('coverage_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('command', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('DEGRADED', 'Degraded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout_reference', models.CharField(blank=True, default='', max_length=1024)),
                ('stderr_reference', models.CharField(blank=True, default='', max_length=1024)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('coverage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='jobs.scanjob')),
                ('scan_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='jobs.scanrun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(db_index=True, max_length=32)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('asset_value', models.CharField(blank=True, db_index=True, default='', max_length=2048)),
                ('observed', models.BooleanField(db_index=True, default=True)),
                ('metadata_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='targets.target')),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='jobs.scanrun')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['target', 'asset_type', 'observed_at'], name='jobs_asseto_target__a81901_idx')],
            },
        ),
    ]
