# Generated by Django 5.2.17 on 2026-09-28 10:22

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def preserve_legacy_run_id(apps, schema_editor):
    """Copy the free-form ``ScanJob.run_id`` into ``run_id_legacy`` before the
    column is dropped.

    This MUST run before ``RemoveField(run_id)``. Doing it in a later migration
    is impossible: by then the old values are already gone.
    """
    ScanJob = apps.get_model("jobs", "ScanJob")
    updated = ScanJob.objects.exclude(run_id="").update(run_id_legacy=F("run_id"))
    if updated:
        import logging

        logging.getLogger(__name__).info(
            "preserved legacy run_id for %s ScanJob rows", updated
        )


def discard_legacy_run_id(apps, schema_editor):
    """Reverse: the audit column is dropped along with the original, nothing to do."""

class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_asset_type"),
        ("jobs", "0003_scanrun_toolexecution_assetobservation"),
        ("targets", "0006_seed_owner_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanjob",
            name="run_id_legacy",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Pre-migration free-form run id, kept for audit only.",
                max_length=64,
            ),
        ),
        migrations.RunPython(preserve_legacy_run_id, discard_legacy_run_id),
        migrations.RemoveField(
            model_name="scanjob",
            name="run_id",
        ),
        migrations.AddField(
            model_name="assetobservation",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations",
                to="jobs.scanjob",
            ),
        ),
        migrations.AddField(
            model_name="assetobservation",
            name="tool_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="observations",
                to="jobs.toolexecution",
            ),
        ),
        migrations.AddField(
            model_name="jsanalysisjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scanjob",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.scanrun",
            ),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("OPERATOR", "Operator requested"),
                    ("TARGET_PAUSED", "Target paused"),
                    ("TARGET_ARCHIVED", "Target archived"),
                    ("AUTH_EXPIRED", "Authorization expired"),
                    ("AUTH_REVOKED", "Authorization revoked"),
                    ("TARGET_DISABLED", "Target disabled"),
                ],
                db_index=True,
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scanrun",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("CRASH", "Process crashed / killed by signal"),
                    ("NONZERO_EXIT", "Tool exited non-zero"),
                    ("TIMEOUT", "Timed out"),
                    ("CANCELLED", "Cancelled by operator or kill switch"),
                    ("LAUNCH_FAILED", "Could not start the tool"),
                ],
                db_index=True,
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("PARTIAL", "Partial"),
                    ("CANCELLED", "Cancelled"),
                    ("PAUSED", "Paused"),
                    ("SKIPPED", "Skipped"),
                    ("CANCELLED_KILL_SWITCH", "Cancelled (target kill switch)"),
                ],
                db_index=True,
                default="QUEUED",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="jsanalysisjob",
            index=models.Index(
                fields=["target", "status"], name="jobs_jsanal_target__31fd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jsanalysisjob",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="jobs_jsanal_status_91f4c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["target", "status"], name="jobs_scanjo_target__1af94c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanjob",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="jobs_scanjo_status_91e6f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["target", "status"], name="jobs_scanru_target__79bd07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanrun",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="jobs_scanru_status_ba56d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolexecution",
            index=models.Index(
                fields=["target", "status"], name="jobs_toolex_target__6d3b57_idx"
            ),
        ),
    ]
