# Generated by Django 5.2.17 on 2026-09-28 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_preserve_legacy_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jsanalysisjob",
            name="scan_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="js_analyses",
                to="jobs.scanrun",
            ),
        ),
    ]
