# Generated by Django 5.2.17 on 2026-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_exportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseline",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("RUNNING", "Running"),
                    ("COMPLETE", "Complete"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="NOT_STARTED",
                max_length=16,
            ),
        ),
    ]
