# Generated by Django 6.1.1 on 2026-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_discovered_by_job_and_more'),
        ('targets', '0002_target_notification_config_target_scan_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='path',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='httpservice',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='httpservice',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='httpservice',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='httpservice',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='javascriptasset',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='javascriptasset',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='javascriptasset',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='javascriptfinding',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='js_findings', to='targets.target'),
        ),
        migrations.AddField(
            model_name='port',
            name='banner',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='port',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='port',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='port',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='port',
            name='product',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='port',
            name='version',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='technology',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='technology',
            name='priority_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technology',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='urlasset',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='urlasset',
            name='priority',
            field=models.CharField(db_index=True, default='LOW', max_length=16),
        ),
        migrations.AddField(
            model_name='urlasset',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AlterField(
            model_name='cve',
            name='status',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('potentially_affected', 'Potentially affected'), ('validation_pending', 'Validation pending'), ('validated', 'Validated'), ('not_affected', 'Not affected'), ('expired', 'Expired'), ('resolved', 'Resolved'), ('unknown', 'Unknown')], db_index=True, default='candidate', max_length=32),
        ),
        migrations.AlterField(
            model_name='port',
            name='state',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AlterField(
            model_name='securityfinding',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('VALIDATED', 'Validated'), ('REOPENED', 'Reopened'), ('FALSE_POSITIVE', 'False positive'), ('RESOLVED', 'Resolved'), ('UNKNOWN', 'Unknown')], db_index=True, default='NEW', max_length=16),
        ),
    ]
