# Generated by Django 6.1.1 on 2026-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_apiendpoint_fingerprint_apiendpoint_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='lifecycle',
            field=models.CharField(db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AlterField(
            model_name='port',
            name='state',
            field=models.CharField(db_index=True, default='open', max_length=16),
        ),
    ]
