# Generated by Django 6.1.1 on 2026-09-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_port_lifecycle_alter_port_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='confirmed_dedicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='shared_suspect',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
