# Generated by Django 5.2.17 on 2026-09-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_backfill_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("DOMAIN", "Domain"),
                    ("SUBDOMAIN", "Subdomain"),
                    ("IP", "IP"),
                    ("PORT", "Port"),
                    ("HTTP_SERVICE", "HTTP service"),
                    ("URL", "URL"),
                    ("API_ENDPOINT", "API endpoint"),
                    ("JS_FILE", "JS file"),
                    ("TECHNOLOGY", "Technology"),
                    ("CVE", "CVE candidate"),
                    ("FINDING", "Security finding"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
