# Generated by Django 5.2.17 on 2026-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_alter_asset_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="technology",
            name="cve_checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
