# Generated by Django 5.2.17 on 2026-09-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_technology_cve_checked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="javascriptasset",
            name="current_secret_keys",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
