# Generated by Django 6.1.1 on 2026-09-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('targets', '0002_target_notification_config_target_scan_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='targets.target'),
        ),
    ]
